# 서버 포트 설정
server:
  port: ${PORT:8082}

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: user_codingrecipe
    #password: 1234
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

# 네이버 뉴스 API
naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}