name: Spring Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Spring
        run: |
          ./gradlew clean build -x test
      
      - name: Rename jar
        run: |
          cp build/libs/*SNAPSHOT.jar app.jar

      - name: Debug
        run: ls -al app.jar

      - name: Upload jar
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "app.jar"
          target: "/home/ec2-user/app/"
        
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f app.jar || true

            setsid java -jar /home/ec2-user/app/app.jar \
            > /home/ec2-user/app/app.log 2>&1 < /dev/null &

            exit 0
